Add experimental support for controlling wheels targets
OpenAstronomy/azure-pipelines-templates pull request #51
Opened 2020-09-09 13:52 UTC by Cadair

----

#

2020-09-09 15:11 UTC, Cadair commented on setup.py
> +print(ext_modules)
```suggestion
```

2020-09-09 21:42 UTC, astrofrog requested changes
Works nicely! Just a couple of small comments below.

2020-09-09 21:42 UTC, astrofrog commented on docs/publish.rst
> +``win``, ``macosx`` or ``manylinux`` to be able to select the operating system
maybe it's enough to say ``macos`` and ``linux`` since that should be sufficient?

2020-09-09 21:42 UTC, astrofrog commented on publish.yml
>        condition: succeeded()
Set a displayname to the original target?

2020-09-09 21:42 UTC, astrofrog commented on publish.yml
> +        ${{ if or(eq(target, 'wheels_macos'), contains(target, 'macosx')) }}:
Why not just:

```
        ${{ if or(contains(target, 'macos')) }}:
```

Since that should be unambiguous? Same for other OSes.

2020-09-10 09:26 UTC, Cadair commented
@astrofrog I think I addressed all your points, do you want to restart the astropy PR to test it once more?

2020-09-10 23:24 UTC, astrofrog commented
I've restarted the CI on the astropy PR

2020-09-11 05:08 UTC, astrofrog approved these changes
Works great, thanks!

2020-09-11 05:08 UTC, merged